version: '3.8'

services:
  web:
    container_name: web
    image: kite01/shop
    restart: always
    ports:
      - '80:9898'
    volumes:
      - ./app/shop:/app/shop
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'shop'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_TCP_PORT: '3306'
      MYSQL_DATA_DIR: /var/lib/mysql
    volumes:
      - ./mysql:/var/lib/mysql